### ISSUE TITLE
use whois query for clouds that don't publish an IP list?

### ISSUE THREAD

**Issue by batuhan** [bcoe/which-cloud#9]
It would reveal who owns the IP and then you can match that organization name to a cloud service. It wouldn't give the region information tho.

For example try running `$ whois 40.112.124.0 | grep OrgName` and it will respond with Microsoft.

**Comment by batuhan** [comment]
Looking at the code (I've only checked the data directory before opening this issue, my bad), this could be fallback for other providers.

**Comment by bcoe** [comment]
When reading up on approaches for narrowing down the various cloud providers, I came across this analysis of Amazon's cloud:

> Amazon [has] actually made the registrations under several different regional registrars and under several different organizations within some of the registrars.

Indicating to me that the data could be somewhat noisy using `whois` ... but YES I like the idea of using `whois` for the providers I currently have no idea of how to lookup.

Looks like this would be a good start:

https://www.npmjs.com/package/whois
